package com.z7dream.upload.lib.db.bean;

import android.text.TextUtils;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by Z7Dream on 2017/6/22 11:28.
 * Email:zhangxyfs@126.com
 */
@Entity
public class OSSProviderInfo {
    @Id(assignable = true)
    private long id;

    private Long nowLoginUserId;//当前登录用户

    private Long companyId;//公司id

    private String securityToken;

    private String accessKeySecret;

    private String accessKeyId;

    private String expiration;

    private long time;

    private String endPoint;

    private String bucketName;

    private boolean isPublic;

    public boolean isNull() {
        return TextUtils.equals(bucketName, "xxxx") || TextUtils.equals(accessKeyId, "xxxx") || id == 0L;
    }

    @Generated(70722688)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public OSSProviderInfo(long id, Long nowLoginUserId, Long companyId, String securityToken,
            String accessKeySecret, String accessKeyId, String expiration, long time, String endPoint,
            String bucketName, boolean isPublic) {
        this.id = id;
        this.nowLoginUserId = nowLoginUserId;
        this.companyId = companyId;
        this.securityToken = securityToken;
        this.accessKeySecret = accessKeySecret;
        this.accessKeyId = accessKeyId;
        this.expiration = expiration;
        this.time = time;
        this.endPoint = endPoint;
        this.bucketName = bucketName;
        this.isPublic = isPublic;
    }

    @Generated(685078241)
    public OSSProviderInfo() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getNowLoginUserId() {
        return nowLoginUserId;
    }

    public void setNowLoginUserId(Long nowLoginUserId) {
        this.nowLoginUserId = nowLoginUserId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public String getSecurityToken() {
        return securityToken;
    }

    public void setSecurityToken(String securityToken) {
        this.securityToken = securityToken;
    }

    public String getAccessKeySecret() {
        return accessKeySecret;
    }

    public void setAccessKeySecret(String accessKeySecret) {
        this.accessKeySecret = accessKeySecret;
    }

    public String getAccessKeyId() {
        return accessKeyId;
    }

    public void setAccessKeyId(String accessKeyId) {
        this.accessKeyId = accessKeyId;
    }

    public String getExpiration() {
        return expiration;
    }

    public void setExpiration(String expiration) {
        this.expiration = expiration;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public String getEndPoint() {
        return endPoint;
    }

    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint;
    }

    public String getBucketName() {
        return bucketName;
    }

    public void setBucketName(String bucketName) {
        this.bucketName = bucketName;
    }

    public boolean getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(boolean isPublic) {
        this.isPublic = isPublic;
    }
}
