package com.z7dream.upload.lib.db.bean;

import com.alibaba.sdk.android.oss.internal.OSSAsyncTask;
import com.z7dream.upload.lib.listener.UploadListener;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by Z7Dream on 2017/6/22 11:28.
 * Email:zhangxyfs@126.com
 */
@Entity
public class TaskInfo {
    @Id
    private long id;

    private String taskKey;//标识，url的hashcode

    private String fileName;//文件名

    private String filePath;//文件路径

    private String originalFilePath;//原图路径

    private String toUploadPath;//上传到的地址

    private String fileUrl;//文件url

    private float progress;//进度

    private long currentSize;//当前大小

    private long totalLength;////总大小

    private long networkSpeed;//速度

    private int state = 0;//当前状态

    private int status;//是下载还是上传

    private int createTime;//创建任务时候的时间戳

    private int succTime;//上传成功时候的时间戳

    private String bucketName;

    private String endPoint;

    private Long userId;

    private Long companyId;

    private int retryNum;//重新上传的次数，大于3次就不再重新上传

    @Transient
    public OSSAsyncTask ossAsyncTask;//上传任务

    @Transient
    private UploadListener uploadCallback;//回掉


    @Generated(36876594)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public TaskInfo(long id, String taskKey, String fileName, String filePath,
            String originalFilePath, String toUploadPath, String fileUrl,
            float progress, long currentSize, long totalLength, long networkSpeed,
            int state, int status, int createTime, int succTime, String bucketName,
            String endPoint, Long userId, Long companyId, int retryNum) {
        this.id = id;
        this.taskKey = taskKey;
        this.fileName = fileName;
        this.filePath = filePath;
        this.originalFilePath = originalFilePath;
        this.toUploadPath = toUploadPath;
        this.fileUrl = fileUrl;
        this.progress = progress;
        this.currentSize = currentSize;
        this.totalLength = totalLength;
        this.networkSpeed = networkSpeed;
        this.state = state;
        this.status = status;
        this.createTime = createTime;
        this.succTime = succTime;
        this.bucketName = bucketName;
        this.endPoint = endPoint;
        this.userId = userId;
        this.companyId = companyId;
        this.retryNum = retryNum;
    }

    @Generated(2022720704)
    public TaskInfo() {
    }


    public UploadListener getUploadCallback() {
        return uploadCallback;
    }

    public void setUploadCallback(UploadListener uploadCallback) {
        this.uploadCallback = uploadCallback;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTaskKey() {
        return taskKey;
    }

    public void setTaskKey(String taskKey) {
        this.taskKey = taskKey;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getOriginalFilePath() {
        return originalFilePath;
    }

    public void setOriginalFilePath(String originalFilePath) {
        this.originalFilePath = originalFilePath;
    }

    public String getToUploadPath() {
        return toUploadPath;
    }

    public void setToUploadPath(String toUploadPath) {
        this.toUploadPath = toUploadPath;
    }

    public String getFileUrl() {
        return fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public float getProgress() {
        return progress;
    }

    public void setProgress(float progress) {
        this.progress = progress;
    }

    public long getCurrentSize() {
        return currentSize;
    }

    public void setCurrentSize(long currentSize) {
        this.currentSize = currentSize;
    }

    public long getTotalLength() {
        return totalLength;
    }

    public void setTotalLength(long totalLength) {
        this.totalLength = totalLength;
    }

    public long getNetworkSpeed() {
        return networkSpeed;
    }

    public void setNetworkSpeed(long networkSpeed) {
        this.networkSpeed = networkSpeed;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreateTime() {
        return createTime;
    }

    public void setCreateTime(int createTime) {
        this.createTime = createTime;
    }

    public int getSuccTime() {
        return succTime;
    }

    public void setSuccTime(int succTime) {
        this.succTime = succTime;
    }

    public String getBucketName() {
        return bucketName;
    }

    public void setBucketName(String bucketName) {
        this.bucketName = bucketName;
    }

    public String getEndPoint() {
        return endPoint;
    }

    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public int getRetryNum() {
        return retryNum;
    }

    public void setRetryNum(int retryNum) {
        this.retryNum = retryNum;
    }
}
